### PR TITLE
BZ#1241799 Backport XML / XSLT changes from upstream

### PR DESCRIPTION
**Pull request by ctomc**
Moves xml api usage to be created via JAXP in central place which is XmlUtils.
Where extra configuration is done to create "secure processing" parsers.
https://bugzilla.redhat.com/show_bug.cgi?id=1241799

### CODE REVIEW

**Comment by dmlloyd** [comment]
You're going to need to explain why changing the license is OK.  If you've just replaced all that code with code from upstream, that's fine, just say so in the PR description.

BTW, the PR description is included in the permanent commit so maybe you want something better than "this should do it".

Now I feel like I need to update my "good PRs" doc...

**Comment by wolfc** [comment]
I'm still sceptical as the formatting changes cloud the actual changes. While the actual changes must be kept to a minimum.

**Comment by ctomc** [comment]
@dmlloyd yes license change is just replacement of files from upstream.
the PR description looking in retrospect is bad. It was written in context of discussion I had with Carlo.

@wolfc beyond adding some tests, this is pretty much the minimum changeset.
This is result of moving creation of "xml classes" to use JAXP and doing that in single place which is XmlUtils class.
All other changes just reflect that.

**Comment by wolfc** [comment]
Merged

**Pull request closed without merging**
